[LANGUAGE]
Type=0
[CSP]
CSP Name=HengBao UranuSafe Mof CSP V3.0
[PKCS11]
DLLName=HBPKCS11.dll
[TSP]
;私有:1,无驱:2,PCSC:4,CCID:8,SCID:16,HID 32 如果要支持多种设备类型 就取各个设备类型或的结果 比如1|2=3
ProductType=34
;如果要支持多种标签中间加#号,比如hengbao 最长不能超过260
BotKeyTag=hengbao
PcscBotKeyTag=Prod_UranuSafe_Key
PcscKeyTag=HB UranuSafe Key#FT SCR2000A
HIDManufacturerTag=HengBao
;如果要支持多种标签中间加#号,比如UranuSafe Key＃UranuSafe KU 最长不能超过260
HIDProductTag=UranuSafe Key
[TOOL]
AutoImportIE=1
CertInfoSplash=0
InitPinDlg=1
AutorunFileName=
AutoRun=0
AutoClose=1
[PIN]
SessionPin=0
