# 本文件是 CommonLog.dll 的配置文件
#
# 配置说明
#
# logLevel 日志级别(可配置 trace warning error默认是trace)
# logPath 日志公共路径
# logFileMaxSize 日志文件最大尺寸(以M为单位) 默认是1M
# DirName 具体的日志路径(日志文件的路径)
#
[PublicConfig]
LogFileMaxSize =10485760
LogPath =C:\BJCAROOT\BJCAlog\

[XTXConfig]
LogLevel=trace
DirName =xtx
TradeLogPath =C:\BJCAROOT\xtxtradelog\xtx_trade.log
YZTChannelIds = 510&528&834&600&540&735&543

[XTXCoreSvr2]
LogLevel = trace
DirName =XTXCoreSvr2

