[SmartCTCAPIHID]
dllversion=2.0.1.913
setlogpath=1
logname=SmartCTCAPIHID1
logpath=C:\BJCAROOT\Ukeylog\
loglevel=2
;0不打印 1 error 2 info

[axtx5018_gm]
dllversion=2.0.1.913
setlogpath=1
logname=axtx5018_gm1
logpath=C:\BJCAROOT\Ukeylog\
loglevel=2
;0不打印 1 error 2 info
