# 本文件是 XTXAppCOM.dll 的配置文件
#
# 配置说明
#
# logLevel 日志级别(可配置 trace warning error nolog 默认是error)
# logPath 日志路径(日志文件的路径，存在时写日志)
# logFileMaxSize 日志文件最大尺寸(以M为单位) 默认是1M
# CSSUpdateCert 校验PIN码成功后 是否调用CSS更新证书 配置为true或false 默认为false
# BJCACertOnly 是否只识别BJCA签发的证书 配置为true或false 默认是false
# ProgressPrompt 是否弹出提示"正在读取证书请稍后"的提示框 配置为true或false 默认是true
# WriteFileNeedPIN 写文件时是否必须验证PIN码 配置为true或false 默认为false
# PinValidity口令有效期配置为0，30，90，180天
# PinRules长度为6-16的所有字符
[XTXConfig]
LogLevel =trace
LogPath =C:\BJCAROOT\BJCAlog\xtx\
LogFileMaxSize =10485760
CSSUpdateCert = true
BJCACertOnly = false
ProgressPrompt = true
WriteFileNeedPIN = false
TradeLogPath =C:\BJCAROOT\xtxtradelog\xtx_trade.log
YZTChannelIds = 600&2614&834&510&3071&100021
PinValidity=0
PinRules=^.{6,16}$

#是否加载其它插件 0：不启用 1：启用
LoadYQDPlugin=0
LoadXBYPlugin=0
LoadXTPlugin=0
UploadLogToJGPT=0
[JGPTConfig]
ServerHost=http://192.168.112.69:10301
ServerTimeout=20
LogLevel=error
LogFile=scpb_jgpt.log
RetryCount=5
RetryInterval=2
UploadInterval=30
