[Default]
# 服务启动类型 1：system用户（默认值）， 2：当前用户 
ServiceRunType = 1
# 是否使用扩展CertId 默认使用 1：使用，0：不使用
ExtendCertId = 0 
# 1：detached（默认值），0：非detached
ProcDetached = 1
#连接数，默认值300 
ThreadsPerChild = 300
#是否允许Ajax跨域访问，默认值为2：不做任何操作，1：允许，0：不允许
InsecurePrivateNetworkRequestsAllowed = 2

#V3.8.2 - begin 
ServicePluginRegPathForWebsvr = SOFTWARE\BJCA\xtxcore2\websvr
ServicePluginRegPathForTimer = SOFTWARE\BJCA\xtxcore2\timer
OpenCurrentUserDesktop=1
#V3.8.2 - end

#V3.8.4 - begin 
#1：使用 2：不使用，默认值为1（使用）
use_thread_mutex_getprocinfo = 1
#V3.8.4 - end

[axhost]
#V3.8.2 - begin
# 需要扩展certid的xtx控件 (length 38) 必须是这种格式 默认值为产品XTXClsId 
XTXClsid = {3F367B74-92D9-4C5E-AB93-234F8A91D5E6}
LogFilePath=C:\BJCAROOT\BJCAlog\XTXCoreSvr\axhost.log
#trace warning error nolog 默认值：trace 
LogLevel=trace
#V3.8.2 - end
