#driver.ini文件说明
#[BJCA] 名字为密码服务提供者的名字 可以自定义名称
#type 标识该设备的类型 目前支持的类型为 SKF BJCAKey CSP
#vid 硬件设备的Vendor ID
#pid 硬件设备的Product ID
#dll 硬件设备所依赖的动态库 在类型为SKF和BJCAKey时有效
#csp 硬件设备对应的CSP名称 在类型为BJCAKey和CSP时有效

#如果添加新支持的设备 请按照如下例子添加
#[Feitian GM]
#type = SKF
#vid = 0x096E
#pid = 0x0303
#dll = FTGM.dll

#[Feitian3K]
#type = BJCAKey
#vid = 0x096E
#pid = 0x0401
#dll = bjcakey_ft3k.dll
#csp = "EnterSafe CSP (ePass3000) v1.0 for BJCA"

#[Feitian2K]
#type = csp
#vid = 0x096E
#pid = 0x0801
#csp = "EnterSafe CSP (ePass2000-FT11) v1.0 for BJCA"

[LG3073]
type = SKF
vid = 0x6588
pid = 0x1514
dll = lgu3073_p1514_gm.dll

[ZTXA]
type = SKFGB
vid = 0x22FB
pid = 0x1014
dll = USK218_GM.dll

[ZTXA1011]
type = SKFGB
vid = 0x22FB
pid = 0x1011
dll = USK218_P1011_GM.dll

[ZTXA1611]
type = SKF
vid = 0x22FB
pid = 0x1611
dll = USK217_GM.dll

#[ZTXA]
#type = BJCAKey
#vid = 0x22FB
#pid = 0x1014
#dll = bjcakey_usk.dll
#csp = "UltraSec USK218 CSP V1.0 for BJCA"